import './globals.css'
import { Inter } from 'next/font/google'
import MyContextProvider from './MyContext'
import Navbar from './nav'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {



  
  return (
    <html lang="en">
      <meta name="google" content="notranslate"></meta>
   
      <body className={inter.className}>
        <MyContextProvider>
          <Navbar/>
          {children}
        </MyContextProvider>

      </body>
   
    </html>
  )
}
