import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'
import MyContextProvider from './MyContext'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
   
      <body className={inter.className}>
        <MyContextProvider>
          {children}
        </MyContextProvider>

      </body>
   
    </html>
  )
}
